//====================================================================================================
// Base code generated with LeatherGoods - ASF.Business
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ASF.Entities;
using ASF.Data;


namespace ASF.Business
{
    /// <summary>
    /// CountryBusiness business component.
    /// </summary>
    public class CountryBusiness
    {
        /// <summary>
        /// Add method. 
        /// </summary>
        /// <param name="Country"></param>
        /// <returns></returns>
        public Country Add(Country Country)
        {
            var CountryDAC = new CountryDAC();
            return CountryDAC.Create(Country);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        public void Remove(int id)
        {
            var CountryDAC = new CountryDAC();
            CountryDAC.DeleteById(id);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public List<Country> All()
        {
            var CountryDAC = new CountryDAC();
            var result = CountryDAC.Select();
            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public Country Find(int id)
        {
            var CountryDAC = new CountryDAC();
            var result = CountryDAC.SelectById(id);
            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="Country"></param>
        public void Edit(Country Country)
        {
            var CountryDAC = new CountryDAC();
            CountryDAC.UpdateById(Country);
        }
    }
}
